name: Daily Scrape, Analyze, and Deploy

on:
  # Schedule the workflow to run daily at 20:00 UTC
  # schedule:
  #   - cron: '0 18 * * *' # UTC timezone (18:00 UTC = 20:00 CEST)

  # Allow manual triggering of the workflow from the GitHub Actions tab
  workflow_dispatch: {}

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  scrape:
    uses: ./.github/workflows/scrape.yml
    secrets: inherit

  process:
    needs: scrape
    uses: ./.github/workflows/process.yml
    with:
      download_artifact_locally: true
    secrets: inherit

  deploy:
    needs: process
    if: needs.process.outputs.data_changed == 'true'
    uses: ./.github/workflows/reusable-build-deploy.yml
    secrets: inherit
    with:
      ref: ${{ needs.process.outputs.new_commit_sha }}
