name: Scrape and Analyze MINV

on:
  workflow_dispatch:
  workflow_call:
    secrets:
      GEMINI_API_KEY:
        required: true

jobs:
  scrape_analyze_minv:
    runs-on: ubuntu-latest
    steps:
      - name: Install pandoc
        run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Analyzer Environment
        uses: ./.github/actions/analyzer-setup

      - name: minv 1. Get list of districts
        run: python minv/1_zoznam_okresov.py > ../data/minv/1_zoznam_okresov.json
        working-directory: ./analyzer
      - name: minv 1. Upload District List Artifact (for debugging)
        uses: actions/upload-artifact@v4
        with:
          name: minv-1-district-list
          path: ./data/minv/1_zoznam_okresov.json

      - name: minv 2. Get official board contents
        run: python minv/2_uradne_tabule.py --input ../data/minv/1_zoznam_okresov.json --output ../data/minv/2_uradne_tabule.json
        working-directory: ./analyzer
      - name: minv 2. Upload Board Contents Artifact (for debugging)
        uses: actions/upload-artifact@v4
        with:
          name: minv-2-board-contents
          path: ./data/minv/2_uradne_tabule.json

      - name: minv 3. Diff new vs old board contents
        run: python minv/3_diff.py --old ../data/minv/2_uradne_tabule_old.json --new ../data/minv/2_uradne_tabule.json > ../data/minv/3_diff.json || true
        working-directory: ./analyzer
      - name: minv 3. Upload Board Diff Artifact (for debugging)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: minv-3-board-diff
          path: ./data/minv/3_diff.json

      - name: minv 4. Process new documents (convert, analyze)
        run: python minv/4_process_documents.py --input ../data/minv/3_diff.json --docs-dir ../data/minv/docs
        working-directory: ./analyzer
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: minv 5. Archive raw data for next diff
        run: mv ../data/minv/2_uradne_tabule.json ../data/minv/2_uradne_tabule_old.json
        working-directory: ./analyzer

      - name: minv 6. Upload data directory artifact
        uses: actions/upload-artifact@v4
        with:
          name: minv-data
          path: ./data/minv/
          if-no-files-found: error
        if: always()
