name: Build and Deploy Website

on:
  # Allow manual triggering of the workflow from the GitHub Actions tab
  workflow_dispatch: {}

# Set permissions needed for the actions
permissions:
  contents: write # Needed to checkout the repository
  pages: write # Needed to deploy to GitHub Pages
  id-token: write # Needed for the Deploy Pages action (OIDC)

jobs:
  call-build-deploy:
    uses: ./.github/workflows/reusable-build-deploy.yml